/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "inverse-on-surface": "#382e2a",
                "on-primary": "#5c1900",
                "surface-container": "#261e19",
                "error-container": "#93000a",
                "tertiary-container": "#cc7e3b",
                "on-tertiary": "#4e2600",
                "on-surface-variant": "#e3bfb3",
                "primary": "#ffb59c",
                "outline-variant": "#5b4138",
                "primary-fixed": "#ffdbcf",
                "tertiary-fixed-dim": "#ffb77f",
                "on-background": "#f0dfd8",
                "secondary-fixed": "#ffdbcb",
                "surface-dim": "#19120e",
                "surface-variant": "#3d332e",
                "on-primary-container": "#511500",
                "primary-container": "#fa5c1b",
                "secondary-fixed-dim": "#ffb692",
                "error": "#ffb4ab",
                "secondary-container": "#703b1e",
                "surface": "#19120e",
                "tertiary-fixed": "#ffdcc4",
                "on-surface": "#f0dfd8",
                "surface-bright": "#413732",
                "inverse-primary": "#aa3600",
                "surface-container-highest": "#3d332e",
                "on-secondary-fixed": "#341100",
                "on-secondary-container": "#f2a782",
                "on-primary-fixed-variant": "#822800",
                "on-tertiary-fixed": "#2f1500",
                "on-tertiary-container": "#442000",
                "on-error": "#690005",
                "on-secondary": "#522308",
                "primary-fixed-dim": "#ffb59c",
                "inverse-surface": "#f0dfd8",
                "outline": "#aa897f",
                "on-primary-fixed": "#390c00",
                "surface-tint": "#ffb59c",
                "surface-container-low": "#221a16",
                "background": "#19120e",
                "on-error-container": "#ffdad6",
                "tertiary": "#ffb77f",
                "on-tertiary-fixed-variant": "#6f3800",
                "secondary": "#ffb692",
                "surface-container-high": "#312824",
                "surface-container-lowest": "#140d09",
                "on-secondary-fixed-variant": "#6d391c"
            },
            fontFamily: {
                "headline": ["Epilogue", "sans-serif"],
                "body": ["Manrope", "sans-serif"],
                "label": ["Manrope", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "1.5rem", "full": "9999px" },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
}
